BEGIN;

CREATE TABLE IF NOT EXISTS profile (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    university VARCHAR(200),
    degree VARCHAR(200),
    bio TEXT,
    email VARCHAR(255),
    phone VARCHAR(80),
    location VARCHAR(160),
    career_interests TEXT[] NOT NULL DEFAULT '{}',
    avatar_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS experiences (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization VARCHAR(200) NOT NULL,
    role VARCHAR(240) NOT NULL,
    location VARCHAR(160),
    start_date DATE,
    end_date DATE,
    category VARCHAR(120),
    types TEXT[] NOT NULL DEFAULT '{}',
    description TEXT,
    achievements TEXT[] NOT NULL DEFAULT '{}',
    display_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS projects (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(240) NOT NULL,
    category VARCHAR(160),
    types TEXT[] NOT NULL DEFAULT '{}',
    tools TEXT[] NOT NULL DEFAULT '{}',
    description TEXT,
    outcome TEXT,
    related_experience_id INTEGER REFERENCES experiences(id) ON DELETE SET NULL,
    display_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS skills (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_name VARCHAR(160) NOT NULL,
    skill_type VARCHAR(120),
    types TEXT[] NOT NULL DEFAULT '{}',
    level VARCHAR(80),
    evidence TEXT,
    display_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visitor_name VARCHAR(160) NOT NULL,
    email VARCHAR(255) NOT NULL,
    company VARCHAR(200),
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    status VARCHAR(40) NOT NULL DEFAULT 'new',
    CONSTRAINT messages_status_check CHECK (status IN ('new', 'read', 'archived'))
);

ALTER TABLE experiences ADD COLUMN IF NOT EXISTS types TEXT[] NOT NULL DEFAULT '{}';
ALTER TABLE projects ADD COLUMN IF NOT EXISTS types TEXT[] NOT NULL DEFAULT '{}';
ALTER TABLE skills ADD COLUMN IF NOT EXISTS types TEXT[] NOT NULL DEFAULT '{}';

CREATE INDEX IF NOT EXISTS idx_experiences_display_order ON experiences(display_order);
CREATE INDEX IF NOT EXISTS idx_experiences_types ON experiences USING GIN(types);
CREATE INDEX IF NOT EXISTS idx_projects_display_order ON projects(display_order);
CREATE INDEX IF NOT EXISTS idx_projects_types ON projects USING GIN(types);
CREATE INDEX IF NOT EXISTS idx_projects_related_experience_id ON projects(related_experience_id);
CREATE INDEX IF NOT EXISTS idx_skills_display_order ON skills(display_order);
CREATE INDEX IF NOT EXISTS idx_skills_types ON skills USING GIN(types);
CREATE INDEX IF NOT EXISTS idx_messages_created_at ON messages(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_messages_status ON messages(status);

INSERT INTO profile (
    id,
    name,
    university,
    degree,
    bio,
    email,
    phone,
    location,
    career_interests,
    avatar_url
) VALUES (
    1,
    'Yishu Zhang',
    'University College London',
    'BSc Geography and Economics',
    'A UCL Geography and Economics student interested in ESG, fintech, AI product operations and international development.',
    NULL,
    NULL,
    'London, UK',
    ARRAY['ESG', 'Finance', 'AI', 'International Development'],
    NULL
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    university = EXCLUDED.university,
    degree = EXCLUDED.degree,
    bio = EXCLUDED.bio,
    email = EXCLUDED.email,
    phone = EXCLUDED.phone,
    location = EXCLUDED.location,
    career_interests = EXCLUDED.career_interests,
    avatar_url = EXCLUDED.avatar_url,
    updated_at = NOW();

INSERT INTO experiences (
    id,
    organization,
    role,
    location,
    start_date,
    end_date,
    category,
    types,
    description,
    achievements,
    display_order
) VALUES
(
    1,
    'Barclays',
    'Global Transaction Banking Spring Week Intern',
    NULL,
    '2026-04-01',
    '2026-04-30',
    'Finance',
    ARRAY['finance'],
    'Completed training on transaction banking products including cash management, trade finance and FX. Awarded a return offer for the 2027 Summer Internship.',
    ARRAY[
        'Completed training across cash management, trade finance and foreign exchange products.',
        'Developed an understanding of how global transaction banking supports corporate clients.',
        'Awarded a return offer for the 2027 Summer Internship.'
    ],
    1
),
(
    2,
    'UNESCAP-CSAM',
    'Learning and Practice Program Intern',
    NULL,
    '2025-08-01',
    '2025-09-30',
    'ESG / International Development',
    ARRAY['international-development'],
    'Collected and analysed desertification datasets for Turkmenistan and Kazakhstan, and built an Excel database using UN repositories.',
    ARRAY[
        'Collected and analysed desertification datasets for Turkmenistan and Kazakhstan.',
        'Built a structured Excel database using United Nations data repositories.',
        'Supported reports and presentations on environmental data management.'
    ],
    2
),
(
    3,
    'Ernst & Young',
    'Strategy and Transactions Intern',
    NULL,
    '2025-06-01',
    '2025-08-31',
    'Valuation / AI',
    ARRAY['finance', 'ai'],
    'Collected market pricing data, verified financial statements, organised bilingual contracts and tested AI tools for internal evaluation.',
    ARRAY[
        'Collected market pricing data and verified financial statements for valuation work.',
        'Organised bilingual contracts and supporting transaction documents.',
        'Tested AI tools and contributed to internal evaluation reports.'
    ],
    3
),
(
    4,
    'Oxfam',
    'Part-time Volunteer',
    NULL,
    '2024-11-01',
    NULL,
    'Charity / Operations',
    ARRAY['international-development'],
    'Supported donation categorisation, pricing, quality control and Gift Aid communication.',
    ARRAY[
        'Categorised and priced donated goods for retail operations.',
        'Supported product quality control and shop-floor organisation.',
        'Communicated Gift Aid information to donors and customers.'
    ],
    4
),
(
    5,
    'NetEase',
    'Technical Department Intern',
    NULL,
    '2024-03-01',
    '2024-04-30',
    'Tech / Low-code',
    ARRAY['ai'],
    'Operated NetEase Codewave low-code platform and conducted quality assurance for Egg Party.',
    ARRAY[
        'Operated the NetEase Codewave low-code development platform.',
        'Conducted quality-assurance testing for Egg Party.',
        'Documented product issues and supported technical team workflows.'
    ],
    5
)
ON CONFLICT (id) DO UPDATE SET
    organization = EXCLUDED.organization,
    role = EXCLUDED.role,
    location = EXCLUDED.location,
    start_date = EXCLUDED.start_date,
    end_date = EXCLUDED.end_date,
    category = EXCLUDED.category,
    types = EXCLUDED.types,
    description = EXCLUDED.description,
    achievements = EXCLUDED.achievements,
    display_order = EXCLUDED.display_order,
    updated_at = NOW();

INSERT INTO projects (
    id,
    title,
    category,
    types,
    tools,
    description,
    outcome,
    related_experience_id,
    display_order
) VALUES
(
    1,
    'Desertification Data Research',
    'ESG / International Development',
    ARRAY['international-development'],
    ARRAY['Excel', 'UN repositories', 'Data analysis'],
    'Collected and analysed desertification datasets for Turkmenistan and Kazakhstan during the UNESCAP-CSAM internship.',
    'Built an Excel database and supported reports and presentations on environmental data management.',
    2,
    1
),
(
    2,
    'AI Tool Evaluation Reports',
    'AI / Consulting',
    ARRAY['finance', 'ai'],
    ARRAY['AI tools', 'Evaluation framework', 'Business analysis'],
    'Tested and drafted AI evaluation reports during the EY Strategy and Transactions internship.',
    'Supported EY in comparing and selecting effective AI tools for internal use.',
    3,
    2
),
(
    3,
    'Hangzhou High-Tech Industry Growth Report',
    'Economic Geography / Data Analysis',
    ARRAY['international-development'],
    ARRAY['Excel', 'Pages', 'Data visualisation'],
    'Analysed the causes of Hangzhou''s high-tech industry growth through data collection and visualisation.',
    'Produced a 5,000-word report explaining industrial growth from an economic geography perspective.',
    NULL,
    3
),
(
    4,
    'Unemployment and Non-Monetary Cost Analysis',
    'Economics / Quantitative Analysis',
    ARRAY['finance'],
    ARRAY['Excel', 'Statistical analysis'],
    'Analysed tens of thousands of data points for a report on the impact of unemployment on non-monetary costs.',
    'Used quantitative evidence to support economic reasoning and report writing.',
    NULL,
    4
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    types = EXCLUDED.types,
    tools = EXCLUDED.tools,
    description = EXCLUDED.description,
    outcome = EXCLUDED.outcome,
    related_experience_id = EXCLUDED.related_experience_id,
    display_order = EXCLUDED.display_order,
    updated_at = NOW();

INSERT INTO skills (
    id,
    skill_name,
    skill_type,
    types,
    level,
    evidence,
    display_order
) VALUES
(
    1,
    'Excel Data Analysis',
    'Technical / Research',
    ARRAY['finance', 'international-development'],
    'Intermediate',
    'Built Excel databases and analysed environmental and economic datasets.',
    1
),
(
    2,
    'AI Tool Evaluation',
    'AI / Consulting',
    ARRAY['finance', 'ai'],
    'Intermediate',
    'Tested AI tools and contributed to internal evaluation reports during EY internship.',
    2
),
(
    3,
    'Low-code Platform Operations',
    'Technology',
    ARRAY['ai'],
    'Intermediate',
    'Operated NetEase Codewave low-code platform.',
    3
),
(
    4,
    'ESG and Environmental Data Research',
    'Research',
    ARRAY['international-development'],
    'Intermediate',
    'Collected and analysed desertification datasets for UNESCAP-CSAM work.',
    4
),
(
    5,
    'Transaction Banking Fundamentals',
    'Finance',
    ARRAY['finance'],
    'Foundational',
    'Completed Barclays training across cash management, trade finance and FX.',
    5
)
ON CONFLICT (id) DO UPDATE SET
    skill_name = EXCLUDED.skill_name,
    skill_type = EXCLUDED.skill_type,
    types = EXCLUDED.types,
    level = EXCLUDED.level,
    evidence = EXCLUDED.evidence,
    display_order = EXCLUDED.display_order,
    updated_at = NOW();

SELECT setval(pg_get_serial_sequence('profile', 'id'), COALESCE((SELECT MAX(id) FROM profile), 1), true);
SELECT setval(pg_get_serial_sequence('experiences', 'id'), COALESCE((SELECT MAX(id) FROM experiences), 1), true);
SELECT setval(pg_get_serial_sequence('projects', 'id'), COALESCE((SELECT MAX(id) FROM projects), 1), true);
SELECT setval(pg_get_serial_sequence('skills', 'id'), COALESCE((SELECT MAX(id) FROM skills), 1), true);
SELECT setval(pg_get_serial_sequence('messages', 'id'), COALESCE((SELECT MAX(id) FROM messages), 1), true);

COMMIT;
